version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
  node:
    build:
      context: .
      dockerfile: docker/node
    working_dir: /src/webpack
    ipc: host
    volumes:
      - .:/src:cached
      - /src/node_modules
    command: bash -c "(npm install -d) && (npm run dev) && (npm run compile_sass)"

  web:
    build:
      context: .
      dockerfile: docker/dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
      - ~/.ssh:/root/.ssh
    depends_on:
      - db
      - node
    ports:
      - "8000:8000"
