name: CI

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PEP8
      uses: ankitvgupta/pycodestyle-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRECOMMAND_MESSAGE: You have style errors. See them below.
    - name: ESLint
      uses: hallee/eslint-action@1.0.3
      if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        source-root: optional-sub-dir
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - uses: actions/checkout@v1
      - uses: docker://python:3.8.3
      - name: Install Pip Dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: Installing NPM dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: webpack

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run BE Tests
      run: |
        pipenv run python manage.py test
    - name: Run FE Cypress Tests
      run: |
          nohup pipenv run python manage.py runserver 0.0.0.0:8000 &
          npm run build
          npm run test