name: CI

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: PEP8
      run: |
        pip install pycodestyle
        pycodestyle --exculde nodemodules, musicpal/local_settings.py --show-source
    - name: ESLint
      run: |
        cd webpack && npm install eslint
        npm run lint_js

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - uses: docker://python:3.8.3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --system
          npm ci --cache .npm --prefer-offline

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run BE Tests
      run: |
        pipenv run python manage.py test
    - name: Run FE Cypress Tests
      run: |
          nohup pipenv run python manage.py runserver 0.0.0.0:8000 &
          npm run build
          npm run test